# Generated by Django 5.1.4 on 2024-12-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_detath',
            new_name='date_of_death',
        ),
    ]
